project:
  type: website

website:
  title: "CSE 150 Data"
  navbar:
    background: primary
    left:
      - text: "Case Studies"
        icon: fa-tachometer
        href: project.html
      - text: "Case Study Data"
        icon: fa-table
        href: data.html
output_dir: '.'


format:
  html:
    theme: cosmo
    toc: true
    toc-location: left 








